kind: Service
apiVersion: v1
metadata:
  name: data-ingest
  labels:
    spring-cloud-service: data-ingest
spec:
# If you are not running k8s on a local dev box, use LoadBalancer to expose the (changing) Redis pod to the k8s API
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    name: data-ingest
