apiVersion: batch/v1
kind: Job
metadata:
  name: spark-task
spec:
  template:
    metadata:
      name: spark-task
    spec:
      containers:
      - name: spark-task
        image: trisberg/spark-task
        imagePullPolicy: Always
        env:
        - name: SPRING_APPLICATION_JSON
          value: '{"spring.hadoop.fs-uri":"hdfs://hadoop-demo-m:8020", "spring.hadoop.resource-manager-host": "hadoop-demo-m", "spring.hadoop.resource-manager-port": 8032, "spring.hadoop. job-history-address": "hadoop-demo-m:10020", "spark.app-args": ["/demo/input","/demo/top10"], "spring.datasource.url":"jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/test","spring.datasource.driverClassName":"org.mariadb.jdbc.Driver","spring.datasource.username":"root","spring.datasource.password":"yourpassword","spring.datasource.testOnBorrow":true,"spring.datasource.validationQuery":"SELECT 1"}'
      restartPolicy: Never
